In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import yfinance as yf
import pandas_ta as ta
data = yf.download(tickers = '^RUI', start = '2012-03-11',end = '2022-07-10')
data.head(10)

[*********************100%***********************]  1 of 1 completed


Open        High         Low       Close   Adj Close  Volume
Date                                                                          
2012-03-12  759.429993  760.619995  756.840027  759.130005  759.130005       0
2012-03-13  761.450012  773.030029  761.450012  772.979980  772.979980       0
2012-03-14  773.190002  774.679993  769.280029  771.630005  771.630005       0
2012-03-15  772.380005  776.469971  770.739990  776.419983  776.419983       0
2012-03-16  776.559998  778.099976  775.640015  777.130005  777.130005       0
2012-03-19  777.119995  782.549988  776.070007  780.090027  780.090027       0
2012-03-20  778.030029  778.299988  773.119995  777.369995  777.369995       0
2012-03-21  777.559998  778.650024  774.760010  776.150024  776.150024       0
2012-03-22  773.640015  773.640015  768.000000  770.270020  770.270020       0
2012-03-23  770.650024  774.010010  766.869995  772.929993  772.929993       0

In [2]:
# Adding indicators
data['RSI']=ta.rsi(data.Close, length=15)
data['EMAF']=ta.ema(data.Close, length=20)
data['EMAM']=ta.ema(data.Close, length=100)
data['EMAS']=ta.ema(data.Close, length=150)

data['Target'] = data['Adj Close']-data.Open
data['Target'] = data['Target'].shift(-1)

data['TargetClass'] = [1 if data.Target[i]>0 else 0 for i in range(len(data))]

data['TargetNextClose'] = data['Adj Close'].shift(-1)

data.dropna(inplace=True)
data.reset_index(inplace = True)
data.drop(['Volume', 'Close', 'Date'], axis=1, inplace=True)

In [3]:
data_set = data.iloc[:, 0:11]#.values
pd.set_option('display.max_columns', None)

data_set.head(20)
#print(data_set.shape)
#print(data.shape)
#print(type(data_set))

Open        High         Low   Adj Close        RSI        EMAF  \
0   791.440002  795.679993  789.760010  789.760010  46.877256  795.406526   
1   789.869995  792.669983  785.640015  787.179993  44.575540  794.623046   
2   787.179993  794.020020  786.260010  793.440002  50.849388  794.510376   
3   794.580017  801.859985  794.580017  801.599976  57.558969  795.185576   
4   800.669983  805.770020  800.669983  805.039978  60.023875  796.124090   
5   804.140015  806.770020  800.780029  803.330017  58.222935  796.810369   
6   802.549988  802.549988  788.549988  790.340027  46.795154  796.194146   
7   789.599976  791.450012  784.169983  790.429993  46.872532  795.645179   
8   788.020020  788.020020  775.929993  779.619995  39.480532  794.118971   
9   781.330017  783.530029  776.349976  777.270020  38.081714  792.514309   
10  779.770020  783.950012  775.109985  779.429993  40.169328  791.268183   
11  779.369995  781.419983  773.960022  778.669983  39.665161  790.068355   
12  779.330017  782.400024  775.820007  779.349976  40.382463  789.047557   
13  780.809998  788.909973  780.400024  788.700012  49.268081  789.014457   
14  790.809998  792.239990  780.799988  781.150024  43.640756  788.265464   
15  785.229980  785.229980  777.969971  782.940002  45.229834  787.758277   
16  783.739990  791.549988  783.739990  789.090027  50.380084  787.885110   
17  785.340027  785.340027  767.280029  770.789978  38.760053  786.257002   
18  771.270020  774.270020  761.390015  761.390015  34.394185  783.888718   
19  761.359985  768.880005  758.909973  762.609985  35.405917  781.862172   

          EMAM        EMAS     Target  TargetClass  TargetNextClose  
0   775.179523  762.677734  -2.690002            0       787.179993  
1   775.417156  763.002267   6.260010            1       793.440002  
2   775.774044  763.405416   7.019958            1       801.599976  
3   776.285448  763.911304   4.369995            1       805.039978  
4   776.854845  764.456055  -0.809998            0       803.330017  
5   777.379106  764.970942 -12.209961            0       790.340027  
6   777.635758  765.306956   0.830017            1       790.429993  
7   777.889109  765.639712  -8.400024            0       779.619995  
8   777.923384  765.824881  -4.059998            0       777.270020  
9   777.910446  765.976472  -0.340027            0       779.429993  
10  777.940536  766.154664  -0.700012            0       778.669983  
11  777.954981  766.320430   0.019958            1       779.349976  
12  777.982604  766.493007   7.890015            1       788.700012  
13  778.194830  766.787140  -9.659973            0       781.150024  
14  778.253349  766.977376  -2.289978            0       782.940002  
15  778.346154  767.188802   5.350037            1       789.090027  
16  778.558904  767.478884 -14.550049            0       770.789978  
17  778.405064  767.522740  -9.880005            0       761.390015  
18  778.068132  767.441512   1.250000            1       762.609985  
19  777.762030  767.377518  -1.540039            0       762.669983

In [4]:
#Target column Categories
#y =[1 if data.Open[i]>data.Close[i] else 0 for i in range(0, len(data))]
#yi = [data.Open[i]-data.Close[i] for i in range(0, len(data))]
#print(yi)
#print(len(yi))

In [5]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range=(0,1))
data_set_scaled = sc.fit_transform(data_set)
print(data_set_scaled)

[[0.02295817 0.02294337 0.02477161 ... 0.61254467 0.         0.02075971]
 [0.02213767 0.02137597 0.02261574 ... 0.64462357 1.         0.02403152]
 [0.02073185 0.02207898 0.02294016 ... 0.6473474  1.         0.02829634]
 ...
 [0.70292872 0.70530315 0.68624737 ... 0.63741923 1.         0.71234811]
 [0.71004135 0.71485848 0.70603747 ... 0.72379951 1.         0.73006085]
 [0.7151577  0.72731964 0.71872676 ... 0.62397837 1.         0.72869667]]


In [6]:
# multiple feature from data provided to the model
X = []
#print(data_set_scaled[0].size)
#data_set_scaled=data_set.values
backcandles = 30
print(data_set_scaled.shape[0])
for j in range(8):#data_set_scaled[0].size):#2 columns are target not X
    X.append([])
    for i in range(backcandles, data_set_scaled.shape[0]):#backcandles+2
        X[j].append(data_set_scaled[i-backcandles:i, j])

#move axis from 0 to position 2
X=np.moveaxis(X, [0], [2])

#Erase first elements of y because of backcandles to match X length
#del(yi[0:backcandles])
#X, yi = np.array(X), np.array(yi)
# Choose -1 for last column, classification else -2...
X, yi =np.array(X), np.array(data_set_scaled[backcandles:,-1])
y=np.reshape(yi,(len(yi),1))
#y=sc.fit_transform(yi)
#X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
print(X)
print(X.shape)
print(y)
print(y.shape)

2447
[[[2.29581669e-02 2.29433745e-02 2.47716068e-02 ... 1.38101972e-02
   8.97234280e-05 0.00000000e+00]
  [2.21376684e-02 2.13759713e-02 2.26157378e-02 ... 1.33872827e-02
   2.23202774e-04 1.85785313e-04]
  [2.07318516e-02 2.20789762e-02 2.29401625e-02 ... 1.33264641e-02
   4.23668073e-04 4.16575636e-04]
  ...
  [1.03842190e-02 9.06593181e-03 1.25061612e-02 ... 0.00000000e+00
   0.00000000e+00 2.21429917e-03]
  [1.22865199e-02 1.41534449e-02 1.49655357e-02 ... 4.61538131e-04
   4.20465674e-05 2.30721567e-03]
  [1.57200584e-02 1.35233817e-02 1.58550688e-02 ... 8.02521949e-04
   6.66876018e-05 2.38760384e-03]]

 [[2.21376684e-02 2.13759713e-02 2.26157378e-02 ... 1.33872827e-02
   2.23202774e-04 1.85785313e-04]
  [2.07318516e-02 2.20789762e-02 2.29401625e-02 ... 1.33264641e-02
   4.23668073e-04 4.16575636e-04]
  [2.45991637e-02 2.61614837e-02 2.72937711e-02 ... 1.36909305e-02
   7.10925863e-04 7.06181108e-04]
  ...
  [1.22865199e-02 1.41534449e-02 1.49655357e-02 ... 4.61538131e-04
   4.

In [7]:
#also comprehensions for X
#X = np.array([data_set_scaled[i-backcandles:i,:4].copy() for i in range(backcandles,len(data_set_scaled))])
#print(X)
#print(X.shape)

In [8]:
# split data into train test sets
splitlimit = int(len(X)*0.8)
print(splitlimit)
X_train, X_test = X[:splitlimit], X[splitlimit:]
y_train, y_test = y[:splitlimit], y[splitlimit:]
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(y_train)

1933
(1933, 30, 8)
(484, 30, 8)
(1933, 1)
(484, 1)
[[0.01673005]
 [0.01859073]
 [0.01876841]
 ...
 [0.55846903]
 [0.56623563]
 [0.569612  ]]


In [ ]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import Dense
from keras.layers import TimeDistributed

import tensorflow as tf
import keras
from keras import optimizers
from keras.callbacks import History
from keras.models import Model
from keras.layers import Dense, Dropout, LSTM, Input, Activation, concatenate
import numpy as np
#tf.random.set_seed(20)
np.random.seed(10)

lstm_input = Input(shape=(backcandles, 8), name='lstm_input')
inputs = LSTM(150, name='first_layer')(lstm_input)
inputs = Dense(1, name='dense_layer')(inputs)
output = Activation('linear', name='output')(inputs)
model = Model(inputs=lstm_input, outputs=output)
adam = optimizers.Adam()
model.compile(optimizer=adam, loss='mse')
model.fit(x=X_train, y=y_train, batch_size=15, epochs=30, shuffle=True, validation_split = 0.1)

Using TensorFlow backend.
D:\ProgramFiles\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\ProgramFiles\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\ProgramFiles\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\ProgramFiles\Anaconda3\lib\site-packages\tensorflow\python\framework\dtype





Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Train on 1739 samples, validate on 194 samples
Epoch 1/30
1739/1739 [==============================] - 4s 2ms/step - loss: 0.0026 - val_loss: 0.0016
Epoch 2/30
1739/1739 [==============================] - 3s 2ms/step - loss: 1.0109e-04 - val_loss: 0.0013
Epoch 3/30
1739/1739 [==============================] - 3s 2ms/step - loss: 9.2762e-05 - val_loss: 0.0012
Epoch 4/30
1739/1739 [==============================] - 3s 2ms/step - loss: 9.0082e-05 - val_loss: 0.0012
Epoch 5/30
1739/1739 [==============================] - 3s 1ms/step - loss: 8.0987e-05 - val_loss: 0.0011
Epoch 6/30
1739/1739 [==============================] - 3s 1ms/step - loss: 8.2002e-05 - val_loss: 0.0011
Epoch 7/30
1739/1739 [==============================] - 3s 1ms/step - loss: 9.0233e-05 - val_loss: 0.0010
Epoch 8/30
1739/1739 [==============================] - 3s 1ms/step - loss: 7.8398e-05 - val_loss: 0.0010
Epoch 9/3

In [ ]:
y_pred = model.predict(X_test)
#y_pred=np.where(y_pred > 0.43, 1,0)
for i in range(10):
    print(y_pred[i], y_test[i])

In [ ]:
plt.figure(figsize=(16,8))
plt.plot(y_test, color = 'black', label = 'Test')
plt.plot(y_pred, color = 'green', label = 'pred')
plt.legend()
plt.show()